### ISSUE TITLE
Beaglebone

### ISSUE THREAD

**Issue by cloudcoderuwu** [adafruit/Adafruit_Python_MCP3008#1]
Hi I just wanted to make sure this code/the examples worked as shown with the BBB without modification, or if the Adafruit_GPIO library needed to be replaced with Adafruit_BBIO or something. Thanks!

**Comment by tdicola** [comment]
Yep this will work as is with the BeagleBone Black.  It will use the BBIO library for GPIO access and the normal python-spidev module for SPI access.
