### ISSUE TITLE
simpletest.py not working.

### ISSUE THREAD

**Issue by abhijeetarmal** [adafruit/Adafruit_Python_MCP3008#2]
simpletest.py is not working but differential.py is working fine.

**Comment by kattni** [comment]
This library is no longer supported. We have written a library called [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka) that allows for using CircuitPython libraries on SBCs with GPIO. Please see the [Adafruit CircuitPython MCP3xxx library](https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx) for using the MCP3008.
