### ISSUE TITLE
AttributeError - MCP3008 example code

### ISSUE THREAD

**Issue by jedenoon** [adafruit/Adafruit_Python_MCP3008#3]
- Platform/operating system: Raspberry Pi with Raspbian operating system

- Python version (run `python -version` or `python3 -version`):  i use the nano command on my new raspberry pi 3 model B that has the newest version of Raspbian on it

- Error message you are receiving, including any Python exception traces:  File "simpletest.py", line 22, in <module> 
mcp = Adafruit_MCP3008.MCP3008(spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE))
AttributeError: 'module' object has no attribute 'MCP3008'

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): simply ran the simpletest example code
![mcp3008 error](https://user-images.githubusercontent.com/33131361/32418026-008e7eba-c228-11e7-85cc-11cce2b1ea06.PNG)

**Comment by salmanfarisvp** [comment]
Did you installed python library before running the example ...?
if not `sudo pip install adafruit-mcp3008` , install the library first .

**Comment by kattni** [comment]
This library is no longer supported. We have written a library called [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka) that allows for using CircuitPython libraries on SBCs with GPIO. Please see the [Adafruit CircuitPython MCP3xxx library](https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx) for using the MCP3008.
