### ISSUE TITLE
simpletest.py is not working on beaglebone black 

### ISSUE THREAD

**Issue by krishnakanth12** [adafruit/Adafruit_Python_MCP3008#4]
Platform/operating system: Beaglebone Black with Linux beaglebone 4.1.15 GNU/Linux operating system

Python version (run python -version or python3 -version): i use the nano command on my beaglebone black 

Traceback (most recent call last):
  File "simpletest.py", line 17, in <module>
    mcp = Adafruit_MCP3008.MCP3008(clk=CLK, cs=CS, miso=MISO, mosi=MOSI)
  File "build/bdist.linux-armv7l/egg/Adafruit_MCP3008/MCP3008.py", line 42, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/SPI.py", line 167, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/GPIO.py", line 278, in setup
TypeError: argument 1 must be string, not int

![image](https://user-images.githubusercontent.com/20510825/32606925-117ebf20-c57d-11e7-8b67-bb90d37cedf4.png)

anyone faces these type errors so please suggests me that hot to solve this 
THANK YOU

**Comment by krishnakanth12** [comment]
![image](https://user-images.githubusercontent.com/20510825/32607029-8a6c4be6-c57d-11e7-84d0-cf9beff5ace8.png)
code i am using

**Comment by vanderbt** [comment]
I'm having the exact same problem.  Using different pins for CLK, MISO, MOSI and CS.

**Comment by kattni** [comment]
This library is no longer supported. We have written a library called [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka) that allows for using CircuitPython libraries on SBCs with GPIO. Please see the [Adafruit CircuitPython MCP3xxx library](https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx) for using the MCP3008.
