### ISSUE TITLE
Does Adafruit_Python_MCP3008 library support use of MCP3004/3002?

### ISSUE THREAD

**Issue by Kattihatt** [adafruit/Adafruit_Python_MCP3008#6]
Hello and thanks to anyone involved reading this, for all the good work put down! It was very useful to me.

Is it possible to use a MCP3004/3002 and simply address the first four channels without any expected issues? I'm asking because I'm going to include some information about this in an Instructable I'm making, where I use a RPi with a MCP3008, but I want to know if I can recommend people to just as well use a 3004/3002 if it suits their needs better.

**Comment by kattni** [comment]
This library is no longer supported. We have written a library called [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka) that allows for using CircuitPython libraries on SBCs with GPIO. Please see the [Adafruit CircuitPython MCP3xxx library](https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx) for using the MCP3008 or the MCP3004.
